theme: jekyll-theme-minimal
logo: https://www.researchgate.net/profile/Jonathan-Zia-2/publication/343446322/figure/fig9/AS:924824885026817@1597506843958/a-f-Data-from-Pigs-1-6-respectively-plotted-on-first-3-PCA-dimensions-with_W640.jpg
